language: ruby
sudo: required
services: docker
script: travis_retry bundle exec rspec
env:
  global:
  - JJBVERSION=1.6.1
  - GH_USER=thefynx
  - secure: BCC96tdpgrMG43I3C75F+OXwfKbpL7csf7FWZ8CY2Ns3J/EDPdb406uJe+//N5zqbx2hK7/vPRpb65Nmq6d5ghYxihWUl3MbtTs2PfqplHQ8gRaiUMraoCeoYQJxiuHUjAX/ksheiKmE3fRM4w7hMlF/YYJ0HHiMNkNSMUkti0JPWHZ88pMIREnj2Nm2QK7Dgk+xXKa3oMOwDUV9Lv6N9mdnmqvgw/BN+58JqT982PsiJcJs6n55t7hzI7BodOnrIK9q4b4Vw1IQAP13incq+SK9NZEqBDYMiZKgEZShWWppAHG4lUQJHNYcwLQpUj0tlNOA7dlhorhv4p2l2T4U1IMJwpQU9QCplldif4aU/yprf2Zab1BPONzvj+hEI3+v5V7VQu8DHsygIj4imDM0+MDxooKu3QSsg1yeRswiNCP0okvPb6OsLip52u1FYqx49aEe+5SAsKFKv9JxyaMDrbbwXxD4YV0JbE0tofEHWQ+X7I4cBpNomSdWDjOmtvBZ26pgcBxBTI5nx7F/vPo9mIXl1K5SPBV88SL6Pp3QYPM6j0aKheu6IA5WaomdUWoj3INy2k8foAokbBTo/FSu2IBfG+CPxa4G9xoBhsAjmXuB0tdqExlmO+E//SRdyXHUgeWc6DFxrLrszGIvo0Us1102BABGEm/Zn3h9Hk2Gteo=
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$JJBVERSION.b$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GH_USER:$GH_TOKEN@github.com/thefynx/docker-jenkins-job-builder
  --tags
- ls -R
deploy:
  provider: releases
  api_key:
    secure: NWi4mE95s4fU10fmDWjXZl78bR/cuxK+n20aJZ9XJ3e+qYJAZR2IXE2Zjmk0oPmIcE34J/fEKIwOd1DJ0jUBApCGg3li5+0HEBpeXz4NQgdSu4A5S8b/iKcTUUEDl7l3rUoL79TokgKJS3lcX8atfHCv/GVgQ+kLy8D9X1i4E7kgpcvJSgkYCH5RL/YmQP4i34wEA2DauCeYQMkL+hI2XDGyzegZycwqprD+ae0w/JtiGMk5fM3sahp9uOF3tKqSjBShRXw3EshGvpMIQoyycm3+YuFBuetZTtoAp3Zt/wW4B/xV4wWgnscUPpKLRRIjenR05HFkrm7DEYlXXngXt1os2zYL0Lagw9vlwlEw8bQRA0y38gRoA186a2PYjGs3wt1rwX0sExzjb+iKXbrQUXqbAV7wV1Ypu4+zn2z2r8OVOCiFvskvjeozQ2lLpvorUcNExLrh+SFkGjCmWR02M3xtFTnAjffn0K34BulHGDv1eC07BWeBnHnMWa8sWZEK1UFdVzmTTm1IQ1egmKKEATleiAYkoQEBFOhInWT7zNdH/J0ORLFRYzLcM/jH4Ab2ivjvtP0rSPGE5rWmg+VzPaxetRHzVjWnp0HRIr9SGCs9F9hO3dd18ka3d4ZaZu7R48SzUXKN3VZ+Xf4DyCnxy7PvRyn/6Xk8nsPGK2Z5FF0=
  file: Dockerfile
  skip_cleanup: true
  on:
    repo: TheFynx/docker-jenkins-job-builder
    tags: false
